  // Default palette for TDA

  // Little Endian -> RGBA in little endian is 0xAABBGGRR
  //AABBGGRR
  0xFF000000, // Black
  0xFFEFDCB2, // Light Blue
  0xFFF2A231, // Mid Blue
  0xFFFF0000, // Blue
  0xFF32261B, // Dark Blue
  0xFF27CEA3, // Light Green
  0xFF1A8944, // Green
  0xFF4E482F, // Swamp Green
  0xFF6BE2F7, // Yellow
  0xFF3189EB, // Copper
  0xFF2264A4, // Brown
  0xFF2B3C49, // Dark Brown
  0xFF8B6FE0, // Pink
  0xFF3326BE, // Red
  0xFF9D9D9D, // Gray
  0xFFFFFFFF  // White

