#pragma once
/**
* Trillek Virtual Computer - DCPU16N_macros.hpp
* Macros used by DCPU16N implementation
*/

#ifndef __DCPU16N_MACROS_HPP__
#define __DCPU16N_MACROS_HPP__

#define DCPU16N_PHASE_OPFETCH 0
#define DCPU16N_PHASE_NWAFETCH 1
#define DCPU16N_PHASE_NWBFETCH 2
#define DCPU16N_PHASE_UAREAD 3
#define DCPU16N_PHASE_ACUFETCH 4
#define DCPU16N_PHASE_UBREAD 5
#define DCPU16N_PHASE_BCUFETCH 6
#define DCPU16N_PHASE_EXEC 7
#define DCPU16N_PHASE_UBWRITE 8
#define DCPU16N_PHASE_BCUWRITE 9
#define DCPU16N_PHASE_EXECW 10
#define DCPU16N_PHASE_SLEEP 11

#endif
